config/routes.rb
ConfManager::Application.routes.draw do
  resources :conferences

  resources :contacts

  get "dashboard/index"
  get "dashboard/list_calls"
  get "dashboard/update_call_list"
  get "dashboard/update_call_list_from_db"
  get "dashboard/update_participant_list_from_db"
  get "dashboard/update_waiting_room_list"
  get "dashboard/update_conference_list"
  get "dashboard/update_conference_participant_list"
  
  post "dashboard/drop_into_waiting_room"
  post "dashboard/drop_sid_into_conf"
  post "dashboard/hangup_call"
  post "dashboard/hangup_call_immediate"
  post "dashboard/mute_call"
  post "dashboard/unmute_call"

  
  post "ivr/index"
  post "ivr/handle_user_input_from_ivr"
  post "ivr/contact_info"
  post "ivr/address"
  post "ivr/hangup"
  post "ivr/hangup_immediate"
  
  post "ivr/conference_hold"
  post "ivr/conference_join"
  post "ivr/conference_join_failed"
  post "ivr/conference_join_by_name"
  post "ivr/conference_waiting_room"
  

  match ':controller(/:action(.:format))'
  match ':controller(/:action(/:id(.:format)))'

  root :to => 'dashboard#index'

end

app/models/conference.rb
class Conference < ActiveRecord::Base
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = Conference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conferences }
    end
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
    @conference = Conference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /conferences/new
  # GET /conferences/new.json
  def new
    @conference = Conference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /conferences/1/edit
  def edit
    @conference = Conference.find(params[:id])
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = Conference.new(params[:conference])

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render json: @conference, status: :created, location: @conference }
      else
        format.html { render action: "new" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conferences/1
  # PUT /conferences/1.json
  def update
    @conference = Conference.find(params[:id])

    respond_to do |format|
      if @conference.update_attributes(params[:conference])
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference = Conference.find(params[:id])
    @conference.destroy

    respond_to do |format|
      format.html { redirect_to conferences_url }
      format.json { head :ok }
    end
  end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% @conference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :confname %><br />
    <%= f.text_field :confname %>
  </div>
  <div class="field">
    <%= f.label :pin %><br />
    <%= f.text_field :pin %>
  </div>
  <div class="field">
    <%= f.label :sid %><br />
    <%= f.text_field :sid %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conferences/edit.html.erb
<h1>Editing conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

app/views/conferences/index.html.erb
<h1>Listing conferences</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Pin</th>
    <th>Sid</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @conferences.each do |conference| %>
  <tr>
    <td><%= conference.confname %></td>
    <td><%= conference.pin %></td>
    <td><%= conference.sid %></td>
    <td><%= conference.description %></td>
    <td><%= link_to 'Show', conference %></td>
    <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
    <td><%= link_to 'Destroy', conference, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Conference', new_conference_path %>

app/views/conferences/new.html.erb
<h1>New conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

app/views/conferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Confname:</b>
  <%= @conference.confname %>
</p>

<p>
  <b>Pin:</b>
  <%= @conference.pin %>
</p>

<p>
  <b>Sid:</b>
  <%= @conference.sid %>
</p>

<p>
  <b>Description:</b>
  <%= @conference.description %>
</p>


<%= link_to 'Edit', edit_conference_path(@conference) %> |
<%= link_to 'Back', conferences_path %>